using System;
using System.Collections.Generic;

namespace Tossup.Coins
{
    public sealed class ReactorCoin : CoinDef
    {
        public override string Id => "reactor";
        public override string Name => "Reactor";
        public override string Description => "Heads: gain 1 energy and score 1 point. Tails: score 1 point.";
        public override Rarity Rarity => Rarity.Rare;
        public override int Cost => 20;
        public override int EnergyCost => 1;
        public override double Probability => 0.5;
        public override double TieProbability => 0.05;
        public override IReadOnlyList<CoinType> Types { get; } = new[] { CoinType.Steel, CoinType.Chaos };
        public override IReadOnlyList<Effect> Heads { get; } = new[] { Effect.Energy(1), Effect.Score(1) };
        public override IReadOnlyList<Effect> Tails { get; } = new[] { Effect.Score(1) };
        public override IReadOnlyList<Effect> Edge => Effect.HalfOf(Tails, Heads);
        public override CoinMastery Mastery { get; } = new CoinMastery(
            "Energy generated by Reactor", 15, 50, 150,
            "Heads scores +1 point.", "Tails also grants 1 energy.", "Heads scores another +2 points.",
            MasterySides.Heads, MasterySides.Tails, MasterySides.Heads);

        public ReactorCoin()
        {
            On.Game.Effects.Applied += (ctx, e) =>
            {
                if (e.Inst == ctx.Coin && e.Effect?.Type == EffectType.Energy) ctx.Mastery.Add(Math.Max(0, e.EnergyDelta));
            };
            On.Coins.Resolve += (ctx, res) =>
            {
                int level = ctx.Mastery.Level;
                if (res.Result == Side.Heads)
                {
                    if (level >= 1) res.Effects.Add(Effect.Score(1));
                    if (level >= 3) res.Effects.Add(Effect.Score(2));
                }
                else if (res.Result == Side.Tails && level >= 2) res.Effects.Add(Effect.Energy(1));
            };
        }
    }
}
