#!/usr/bin/env python3
"""Generate GitHub Wiki Markdown from the same content dump as the Pages wiki."""

import sys
import shutil
from pathlib import Path

sys.dont_write_bytecode = True
import gen_wiki as site


OUT = Path(sys.argv[2])
PAGES = "https://scholzdev.github.io/tossup/"
MARKER = "<!-- Generated by tools/gen_github_wiki.py; edit the game data instead. -->\n"


def write(name, title, lines):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.md").write_text(
        MARKER + f"# {title}\n\n" + "\n".join(lines).rstrip() + "\n",
        encoding="utf-8",
    )


def link(label, page):
    return f"[{label}]({page})"


def image(group, entry, lang):
    return f"![{localized(group, entry, lang)[0]}]({PAGES}img/{group}/{entry['id']}.png)\n"


def localized(group, entry, lang):
    translation = site.DATA["de"].get(group, {}).get(entry["id"], {}) if lang == "de" else {}
    return translation.get("name", entry["name"]), translation.get("description", entry.get("description", ""))


def page(group, entry, lang):
    prefix = "DE-" if lang == "de" else ""
    return f"{prefix}{group}-{entry['id']}"


def listing(group, entries, lang, title):
    lines = [f"[{ 'English' if lang == 'de' else 'Deutsch' }]({'Home' if lang == 'de' else 'DE-Home'})\n"]
    for entry in entries:
        name, description = localized(group, entry, lang)
        lines.append(f"- {link(name, page(group, entry, lang))} — {description}")
    write(f"{'DE-' if lang == 'de' else ''}{group}", title, lines)


def coin_pages(lang):
    site.LANG = lang
    for coin in site.DATA["coins"]:
        name, description = localized("coins", coin, lang)
        rarity = site.RARITY[coin["rarity"]][0]
        rarity = site.DESTR.get(rarity, rarity) if lang == "de" else rarity
        lines = [image("coins", coin, lang), description, "", f"- **{site.t('Rarity')}:** {rarity}",
                 f"- **{site.t('Heads chance')}:** {site.pct(coin['probability'])}",
                 f"- **{site.t('Shop price')}:** {site.price(coin)} {site.t('gold')}",
                 f"- **{site.t('Energy to flip')}:** {coin.get('energy_cost', 0)}", "",
                 f"## {site.t('Heads')}", ", ".join(site.effect_text(e) for e in coin["heads"]) or site.t("Nothing"), "",
                 f"## {site.t('Tails')}", ", ".join(site.effect_text(e) for e in coin["tails"]) or site.t("Nothing")]
        start, pool, locked = site.coin_availability(coin["id"])
        lines += ["", f"## {site.t('Who can use it')}"]
        for label, ids in ((site.t("Starts in the deck of:"), start),
                           (site.t("Usable in coin sets from the start:"), pool),
                           (site.t("Found in the shop and unlocked by buying it once:"), locked)):
            names = ", ".join(link(localized("characters", site.CHARS[c], lang)[0], f"{'DE-' if lang == 'de' else ''}characters-{c}") for c in ids)
            lines.append(f"- **{label}** {names or site.t('none')}")
        lines += ["", link(site.t("Coins"), f"{'DE-' if lang == 'de' else ''}coins")]
        write(page("coins", coin, lang), name, lines)
    listing("coins", site.DATA["coins"], lang, site.t("Coins"))


def simple_pages(group, image_group, lang, title):
    site.LANG = lang
    for entry in site.DATA[group]:
        name, description = localized(group, entry, lang)
        lines = [image(image_group, entry, lang), description]
        if group == "items":
            lines += ["", f"**{site.t('Price')}:** {entry['cost']} {site.t('gold')}"]
        elif group == "relics":
            lines += ["", f"**{site.t('Price')}:** 25 {site.t('gold')}"]
        elif group == "characters":
            for label, ids in ((site.t("Starting deck"), entry["deck"]),
                               (site.t("Usable in coin sets from the start"), entry["pool"]),
                               (site.t("Found in the shop (unlocked by buying)"), entry["locked"])):
                names = ", ".join(link(localized("coins", site.COINS[c], lang)[0], f"{'DE-' if lang == 'de' else ''}coins-{c}") for c in ids)
                lines += ["", f"## {label}", names or site.t("none")]
        lines += ["", link(title, f"{'DE-' if lang == 'de' else ''}{group}")]
        write(page(group, entry, lang), name, lines)
    listing(group, site.DATA[group], lang, title)


def modifier_page(lang):
    site.LANG = lang
    lines = [f"- **{localized('modifiers', entry, lang)[0]}:** {localized('modifiers', entry, lang)[1]}"
             for entry in site.DATA["modifiers"]]
    write(f"{'DE-' if lang == 'de' else ''}modifiers", site.t("Level modifiers"), lines)


def guide_pages(lang):
    site.LANG = lang
    prefix = "DE-" if lang == "de" else ""
    for guide in site.GUIDES:
        title = guide["title"][lang]
        body = site.guide_text(guide)
        write(prefix + "guide-" + guide["slug"], title, [body, "", link(site.t("Guides"), prefix + "guides")])
    write(prefix + "guides", site.t("Guides"),
          [f"- {link(guide['title'][lang], prefix + 'guide-' + guide['slug'])}" for guide in site.GUIDES])


def home(lang):
    site.LANG = lang
    prefix = "DE-" if lang == "de" else ""
    categories = (("coins", site.t("Coins")), ("items", site.t("Chips")),
                  ("relics", site.t("Prizes")), ("modifiers", site.t("Level modifiers")),
                  ("characters", site.t("Characters")), ("guides", site.t("Guides")))
    lines = [site.t("Tossup is a roguelike about flipping coins: build a small deck, flip one coin at a time, and score points against a quota before your stack runs out. This wiki lists everything in the game."),
             "", " · ".join(link(label, prefix + group) for group, label in categories), "",
             f"[{'Browse the illustrated wiki' if lang == 'en' else 'Illustriertes Wiki öffnen'}]({PAGES}{'de/' if lang == 'de' else ''})", "",
             link("Deutsch" if lang == "en" else "English", "DE-Home" if lang == "en" else "Home")]
    write(prefix + "Home", "Tossup Wiki", lines)
    return categories


if __name__ == "__main__":
    if OUT.exists():
        shutil.rmtree(OUT)
    for language in ("en", "de"):
        coin_pages(language)
        simple_pages("items", "items", language, "Chips" if language == "en" else "Chips")
        simple_pages("relics", "relics", language, "Prizes" if language == "en" else "Prämien")
        simple_pages("characters", "characters", language, "Characters" if language == "en" else "Charaktere")
        modifier_page(language)
        guide_pages(language)
        categories = home(language)
        if language == "en":
            (OUT / "_Sidebar.md").write_text(MARKER + "\n".join(f"- {link(label, group)}" for group, label in categories) + "\n", encoding="utf-8")
    print(f"github wiki: {len(list(OUT.glob('*.md')))} Markdown pages in {OUT}")
